name: Build Application
description: 
inputs:
   build_project_name: 
      required: true
      type: string  
   build_agent: 
      required: true
      type: string  
   build_dir: 
      required: true
      type: string     
   build_project_path: 
      required: true
      type: string     
   build_settings_path: 
      required: true
      type: string     
   platform: 
      required: true
      type: string     
outputs: 
    compiler_component_path:
      value: ${{ steps.setup.outputs.compiler_component_path }}
    
runs:
  using: "composite"
  steps:

  - id: setup
    uses: miyako/4D/.github/actions/install-compiler-component/@v1
    with:
      build_project_name: "GitActions_Demo"
      platform: "macos"

  - name: compile project macos
    if: ${{ startsWith(inputs.platform, 'macos') }}
    run: |
      "${BUILD_AGENT}" "./${BUILD_PROJECT_PATH}" --user-param="${PWD}/${BUILD_SETTINGS_PATH},../../../../${BUILD_DIR}" --headless --skip-onstartup --startup-method=Build --dataless
    shell: bash
    env:  
      BUILD_AGENT: "/Applications/4D 20.5/4D.app"
      BUILD_DIR: "Users/mbp/Desktop/4D Support/Archiv_Support/GitActions/GitActions_Build"
      BUILD_PROJECT_PATH: "Users/mbp/Desktop/4D Support/Archiv_Support/GitActions/GitActions/Project/GitActions.4DProject"
      BUILD_SETTINGS_PATH: "/Users/mbp/Desktop/4D Support/Archiv_Support/GitActions/GitActions/Settings/buildApp.4DSettings"